# Generated by Django 4.0.1 on 2022-04-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Titre')),
                ('description', models.CharField(max_length=400)),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='Images')),
                ('price', models.FloatField(max_length=6, verbose_name='Prix')),
            ],
        ),
    ]
