# Generated by Django 4.0.1 on 2022-04-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=100, verbose_name='adresse')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Code postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
            ],
        ),
    ]
