# Generated by Django 4.0.1 on 2022-04-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupe_hypnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Adresse'),
        ),
    ]
