# Generated by Django 4.0.1 on 2022-04-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.BooleanField(verbose_name='Arrivée')),
                ('checkout', models.BooleanField(verbose_name='Départ')),
            ],
        ),
    ]
