# Generated by Django 4.0.1 on 2022-04-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=50)),
                ('suite', models.CharField(max_length=50)),
                ('checkin', models.DateTimeField(verbose_name='Arrivée')),
                ('checkout', models.DateTimeField(verbose_name='Départ')),
            ],
        ),
    ]
